SET IDENTITY_INSERT [dbo].[Ingredient] ON
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (1, N'cognac')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (2, N'white crème de cacao')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (3, N'light cream')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (4, N'campari')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (5, N'red vermouth')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (6, N'soda water')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (7, N'gin')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (8, N'apricot brandy')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (9, N'calvados')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (10, N'lemon juice')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (11, N'maraschino liqueur')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (12, N'white rum')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (13, N'lime juice')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (14, N'grenadine syrup')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (15, N'triple sec')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (16, N'maraschino')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (17, N'orange bitters')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (18, N'raspberry syrup')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (19, N'egg white')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (20, N'simple syrup')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (21, N'peach bitters')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (22, N'mint leaves')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (23, N'rye whiskey')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (24, N'sweet red vermouth')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (25, N'angostura bitters')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (26, N'pineapple juice')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (27, N'grenadine')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (28, N'orange juice')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (29, N'drops absinthe')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (30, N'drops grenadine')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (31, N'orange twist')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (32, N'cocktail cherry')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (33, N'sugar cube')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (34, N'plain water')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (35, N'dark rum')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (36, N'sugar syrup')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (37, N'brandy')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (38, N'port')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (39, N'egg yolk')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (40, N'scotch whisky')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (41, N'drambuie')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (42, N'absinthe')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (43, N'one sugar cube')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (44, N'peychaud''s bitters')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (45, N'vodka')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (46, N'white crème de menthe')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (47, N'old tom gin')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (48, N'carbonated water')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (49, N'bourbon whiskey')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (50, N'gomme syrup')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (51, N'prosecco')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (52, N'peach purée')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (53, N'coffee liqueur')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (54, N'tomato juice')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (55, N'worcestershire sauce')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (56, N'tabasco')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (57, N'celery salt')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (58, N'pepper')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (59, N'cachaça')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (60, N'lime')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (61, N'sugar')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (62, N'champagne')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (63, N'vodka citron')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (64, N'cointreau')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (65, N'cranberry juice')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (66, N'cola')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (67, N'light rum')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (68, N'disaronno liqueur')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (69, N'disaronno')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (70, N'galliano')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (71, N'cream')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (72, N'crème de menthe')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (73, N'crème de cacao')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (74, N'ginger ale')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (75, N'angostura bitter')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (76, N'irish whiskey')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (77, N'hot coffee')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (78, N'tsp brown sugar')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (79, N'white wine')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (80, N'crème de cassis')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (81, N'tequila')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (82, N'orange curaçao')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (83, N'orgeat syrup')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (84, N'powdered sugar')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (85, N'water')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (86, N'mint')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (87, N'ginger beer')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (88, N'coconut milk')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (89, N'dry vermouth')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (90, N'kirsch')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (91, N'strawberry syrup')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (92, N'grapefruit juice')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (93, N'peach schnapps')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (94, N'cherry liqueur')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (95, N'dom bénédictine')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (96, N'creme de mure')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (97, N'kahlúa')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (98, N'baileys irish cream')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (99, N'grand marnier')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (100, N'raspberry liqueur')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (101, N'pisco')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (102, N'aperol')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (103, N'lillet blanc')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (104, N'sweet vermouth')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (105, N'rum')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (106, N'gold rum')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (107, N'top with prosecco')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (108, N'midori')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (109, N'jägermeister')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (110, N'carrot juice')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (111, N'créme de cassis')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (112, N'lemon juice,')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (113, N'germain')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (114, N'soda')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (115, N'pure alcohol')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (116, N'bénédictine')
INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (117, N'lemon peel')
SET IDENTITY_INSERT [dbo].[Ingredient] OFF
