//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cocktails.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cocktails.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[Cocktail] ON
        ///INSERT INTO [dbo].[Cocktail] ([ID], [Name], [Instructions], [Image], [WikipediaArticleUri]) VALUES (1, N&apos;Brandy Alexander&apos;, N&apos;Shake all ingredients with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.&apos;, N&apos;brandy_alexander.jpg&apos;, N&apos;https://en.wikipedia.org/wiki/Alexander_(cocktail)&apos;)
        ///INSERT INTO [dbo].[Cocktail] ([ID], [Name], [Instructions], [Image], [WikipediaArticleUri]) VALUES (2, N&apos;Americano&apos;, N&apos;Pour the Campari and vermouth over  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _201808200656426_dbo_Cocktail_data {
            get {
                return ResourceManager.GetString("_201808200656426_dbo_Cocktail_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[Ingredient] ON
        ///INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (1, N&apos;cognac&apos;)
        ///INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (2, N&apos;white crème de cacao&apos;)
        ///INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (3, N&apos;light cream&apos;)
        ///INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (4, N&apos;campari&apos;)
        ///INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (5, N&apos;red vermouth&apos;)
        ///INSERT INTO [dbo].[Ingredient] ([ID], [Name]) VALUES (6, N&apos;soda water&apos;)
        ///INSERT INTO [dbo].[Ingred [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _201808200656426_dbo_Ingredient_data {
            get {
                return ResourceManager.GetString("_201808200656426_dbo_Ingredient_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[RecipeRow] ON
        ///INSERT INTO [dbo].[RecipeRow] ([ID], [CocktailID], [Amount], [Unit], [Ingredient_ID]) VALUES (1, 1, CAST(3.00 AS Decimal(18, 2)), 0, 1)
        ///INSERT INTO [dbo].[RecipeRow] ([ID], [CocktailID], [Amount], [Unit], [Ingredient_ID]) VALUES (2, 1, CAST(3.00 AS Decimal(18, 2)), 0, 2)
        ///INSERT INTO [dbo].[RecipeRow] ([ID], [CocktailID], [Amount], [Unit], [Ingredient_ID]) VALUES (3, 1, CAST(3.00 AS Decimal(18, 2)), 0, 3)
        ///INSERT INTO [dbo].[RecipeRow] ([ID], [CocktailID], [Amount] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _201808200656426_dbo_RecipeRow_data {
            get {
                return ResourceManager.GetString("_201808200656426_dbo_RecipeRow_data", resourceCulture);
            }
        }
    }
}
